/* The following code was generated by JFlex 1.7.0-SNAPSHOT tweaked for IntelliJ platform */

package de.endrullis.idea.postfixtemplates.language;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import de.endrullis.idea.postfixtemplates.language.psi.CptTypes;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0-SNAPSHOT
 * from the specification file <tt>Cpt.flex</tt>
 */
class CptLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int WAITING_DESCRIPTION = 2;
  public static final int WAITING_TEMPLATE_CODE = 4;
  public static final int WAITING_TEMPLATE_CODE_CON = 6;
  public static final int WAITING_TEMPLATE_ESC = 8;
  public static final int WAITING_TEMPLATE_VAR_NAME = 10;
  public static final int WAITING_TEMPLATE_VAR_EXPRESSION = 12;
  public static final int WAITING_TEMPLATE_VAR_EXPRESSION_ESC = 14;
  public static final int WAITING_TEMPLATE_VAR_VALUE = 16;
  public static final int WAITING_TEMPLATE_VAR_VALUE_ESC = 18;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9, 9
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [9, 6, 6]
   * Total runtime size is 1696 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[ZZ_CMAP_Z[ch>>12]|((ch>>6)&0x3f)]<<6)|(ch&0x3f)];
  }

  /* The ZZ_CMAP_Z table has 272 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\100\1\200\u010d\100");

  /* The ZZ_CMAP_Y table has 192 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\2\175\3\1\4\5\3\1\5\71\3");

  /* The ZZ_CMAP_A table has 384 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\4\1\2\1\1\1\5\1\3\22\0\1\6\2\0\1\7\1\17\10\0\1\12\1\11\1\0\12\15\1"+
    "\21\2\0\1\10\1\13\2\0\32\15\1\0\1\20\2\0\1\16\1\0\32\15\12\0\1\1\242\0\2\1"+
    "\50\0\1\14\55\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\6\0\1\2\1\3\1\4\1\5\1\6"+
    "\1\2\1\7\1\6\1\10\2\11\2\12\2\1\2\13"+
    "\1\14\4\1\2\15\1\16\1\17\2\20\1\21\1\22"+
    "\3\20\2\23\1\24\3\23\1\25\1\3\1\11\1\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[53];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\22\0\44\0\66\0\110\0\132\0\154\0\176"+
    "\0\220\0\242\0\264\0\306\0\330\0\264\0\352\0\374"+
    "\0\264\0\u010e\0\264\0\u0120\0\u0132\0\u0144\0\u0156\0\u0168"+
    "\0\u017a\0\u018c\0\u019e\0\264\0\u01b0\0\u01c2\0\u01d4\0\u01e6"+
    "\0\u01f8\0\u020a\0\264\0\264\0\u021c\0\u022e\0\264\0\264"+
    "\0\u0240\0\u0252\0\u0264\0\u0276\0\u0288\0\264\0\u029a\0\u02ac"+
    "\0\u02be\0\352\0\u0132\0\u02d0\0\u017a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[53];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\13\6\14\1\15\1\16\1\17\1\20\1\13\1\21"+
    "\2\22\1\23\1\13\1\16\1\24\1\25\1\14\1\25"+
    "\1\26\1\14\1\27\13\24\1\30\1\31\1\14\1\31"+
    "\1\32\1\14\1\33\10\30\1\23\1\34\2\30\1\31"+
    "\1\14\1\31\1\35\1\14\1\35\10\30\1\23\1\34"+
    "\1\30\1\36\2\37\1\40\3\37\13\36\1\41\1\42"+
    "\4\14\1\42\10\41\1\43\1\13\1\44\1\45\1\46"+
    "\4\14\1\46\10\45\1\43\1\47\1\50\1\51\2\52"+
    "\1\53\3\52\13\51\1\54\1\55\4\14\1\55\10\54"+
    "\1\43\1\56\1\50\1\57\2\60\1\61\3\60\13\57"+
    "\23\0\6\14\13\0\2\15\2\0\16\15\11\0\1\22"+
    "\3\0\1\62\1\22\16\0\1\21\17\0\1\22\3\0"+
    "\2\22\3\0\2\24\1\0\2\24\1\0\15\24\1\63"+
    "\1\14\2\63\1\14\1\63\14\24\1\64\1\14\1\64"+
    "\1\26\1\14\1\26\13\24\1\0\3\14\1\27\1\14"+
    "\1\27\13\0\2\30\1\0\2\30\1\0\11\30\2\0"+
    "\2\30\1\65\1\14\2\65\1\14\1\65\10\30\2\0"+
    "\2\30\1\35\1\14\1\35\1\32\1\14\1\32\10\30"+
    "\2\0\1\30\1\0\3\14\1\33\1\14\1\33\13\0"+
    "\1\30\1\35\1\14\2\35\1\14\1\35\10\30\2\0"+
    "\1\30\4\0\1\36\1\0\1\36\14\0\3\14\1\37"+
    "\1\14\1\37\14\0\1\14\1\37\1\14\1\37\1\14"+
    "\1\37\13\0\2\41\4\0\11\41\3\0\1\41\1\42"+
    "\4\14\1\42\10\41\3\0\2\45\4\0\11\45\3\0"+
    "\1\45\1\46\4\14\1\46\10\45\7\0\1\51\1\0"+
    "\1\51\14\0\3\14\1\52\1\14\1\52\14\0\1\14"+
    "\1\52\1\14\1\52\1\14\1\52\13\0\2\54\4\0"+
    "\11\54\3\0\1\54\1\55\4\14\1\55\10\54\7\0"+
    "\1\57\1\0\1\57\14\0\3\14\1\60\1\14\1\60"+
    "\14\0\1\14\1\60\1\14\1\60\1\14\1\60\13\0"+
    "\1\24\1\64\1\14\2\64\1\14\1\64\13\24";

  private static int [] zzUnpackTrans() {
    int [] result = new int[738];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\1\6\0\1\11\2\1\1\11\2\1\1\11"+
    "\1\1\1\11\10\1\1\11\6\1\2\11\2\1\2\11"+
    "\5\1\1\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[53];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  CptLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { yybegin(WAITING_TEMPLATE_CODE_CON); return CptTypes.TEMPLATE_CODE;
            }
          case 22: break;
          case 2: 
            { return TokenType.BAD_CHARACTER;
            }
          case 23: break;
          case 3: 
            { yybegin(YYINITIAL); return TokenType.WHITE_SPACE;
            }
          case 24: break;
          case 4: 
            { yybegin(YYINITIAL); return CptTypes.COMMENT;
            }
          case 25: break;
          case 5: 
            { yybegin(WAITING_DESCRIPTION); return CptTypes.SEPARATOR;
            }
          case 26: break;
          case 6: 
            { yybegin(YYINITIAL); return CptTypes.CLASS_NAME;
            }
          case 27: break;
          case 7: 
            { yybegin(WAITING_TEMPLATE_CODE); return CptTypes.MAP;
            }
          case 28: break;
          case 8: 
            { yybegin(WAITING_TEMPLATE_VAR_NAME); return CptTypes.TEMPLATE_VARIABLE_START;
            }
          case 29: break;
          case 9: 
            { yybegin(YYINITIAL); return CptTypes.TEMPLATE_DESCRIPTION;
            }
          case 30: break;
          case 10: 
            { yybegin(WAITING_DESCRIPTION); return TokenType.WHITE_SPACE;
            }
          case 31: break;
          case 11: 
            { yybegin(WAITING_TEMPLATE_CODE_CON); return TokenType.WHITE_SPACE;
            }
          case 32: break;
          case 12: 
            { yybegin(WAITING_TEMPLATE_ESC); return CptTypes.TEMPLATE_ESCAPE;
            }
          case 33: break;
          case 13: 
            { yybegin(WAITING_TEMPLATE_VAR_NAME); return CptTypes.TEMPLATE_VARIABLE_NAME;
            }
          case 34: break;
          case 14: 
            { yybegin(WAITING_TEMPLATE_CODE_CON); return CptTypes.TEMPLATE_VARIABLE_END;
            }
          case 35: break;
          case 15: 
            { yybegin(WAITING_TEMPLATE_VAR_EXPRESSION); return CptTypes.TEMPLATE_VARIABLE_SEPARATOR;
            }
          case 36: break;
          case 16: 
            { yybegin(WAITING_TEMPLATE_VAR_EXPRESSION); return CptTypes.TEMPLATE_VARIABLE_EXPRESSION;
            }
          case 37: break;
          case 17: 
            { yybegin(WAITING_TEMPLATE_VAR_EXPRESSION_ESC); return CptTypes.TEMPLATE_VARIABLE_EXPRESSION;
            }
          case 38: break;
          case 18: 
            { yybegin(WAITING_TEMPLATE_VAR_VALUE); return CptTypes.TEMPLATE_VARIABLE_SEPARATOR;
            }
          case 39: break;
          case 19: 
            { yybegin(WAITING_TEMPLATE_VAR_VALUE); return CptTypes.TEMPLATE_VARIABLE_VALUE;
            }
          case 40: break;
          case 20: 
            { yybegin(WAITING_TEMPLATE_VAR_VALUE_ESC); return CptTypes.TEMPLATE_VARIABLE_VALUE;
            }
          case 41: break;
          case 21: 
            { yybegin(YYINITIAL); return CptTypes.TEMPLATE_NAME;
            }
          case 42: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
